---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: controller-manager
  namespace: linode-system
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - linode.com
  resources:
  - firewalls
  - instances
  - vpcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - linode.com
  resources:
  - firewalls/finalizers
  - instances/finalizers
  - vpcs/finalizers
  verbs:
  - update
- apiGroups:
  - linode.com
  resources:
  - firewalls/status
  - instances/status
  - vpcs/status
  verbs:
  - get
  - patch
  - update
