//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Instance) DeepCopyInto(out *Instance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Instance.
func (in *Instance) DeepCopy() *Instance {
	if in == nil {
		return nil
	}
	out := new(Instance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Instance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceAlerts) DeepCopyInto(out *InstanceAlerts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceAlerts.
func (in *InstanceAlerts) DeepCopy() *InstanceAlerts {
	if in == nil {
		return nil
	}
	out := new(InstanceAlerts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceBackupSchedule) DeepCopyInto(out *InstanceBackupSchedule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceBackupSchedule.
func (in *InstanceBackupSchedule) DeepCopy() *InstanceBackupSchedule {
	if in == nil {
		return nil
	}
	out := new(InstanceBackupSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceBackups) DeepCopyInto(out *InstanceBackups) {
	*out = *in
	out.Schedule = in.Schedule
	in.LastSuccessful.DeepCopyInto(&out.LastSuccessful)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceBackups.
func (in *InstanceBackups) DeepCopy() *InstanceBackups {
	if in == nil {
		return nil
	}
	out := new(InstanceBackups)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceInterfaces) DeepCopyInto(out *InstanceInterfaces) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceInterfaces.
func (in *InstanceInterfaces) DeepCopy() *InstanceInterfaces {
	if in == nil {
		return nil
	}
	out := new(InstanceInterfaces)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceList) DeepCopyInto(out *InstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Instance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceList.
func (in *InstanceList) DeepCopy() *InstanceList {
	if in == nil {
		return nil
	}
	out := new(InstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceMetadata) DeepCopyInto(out *InstanceMetadata) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceMetadata.
func (in *InstanceMetadata) DeepCopy() *InstanceMetadata {
	if in == nil {
		return nil
	}
	out := new(InstanceMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstancePlacementGroup) DeepCopyInto(out *InstancePlacementGroup) {
	*out = *in
	if in.MigratingTo != nil {
		in, out := &in.MigratingTo, &out.MigratingTo
		*out = new(int64)
		**out = **in
	}
	if in.CompliantOnly != nil {
		in, out := &in.CompliantOnly, &out.CompliantOnly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstancePlacementGroup.
func (in *InstancePlacementGroup) DeepCopy() *InstancePlacementGroup {
	if in == nil {
		return nil
	}
	out := new(InstancePlacementGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceSpec) DeepCopyInto(out *InstanceSpec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AuthorizedKeys != nil {
		in, out := &in.AuthorizedKeys, &out.AuthorizedKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AuthorizedUsers != nil {
		in, out := &in.AuthorizedUsers, &out.AuthorizedUsers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Metadata = in.Metadata
	if in.StackscriptData != nil {
		in, out := &in.StackscriptData, &out.StackscriptData
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	if in.BackupsEnabled != nil {
		in, out := &in.BackupsEnabled, &out.BackupsEnabled
		*out = new(bool)
		**out = **in
	}
	out.Interfaces = in.Interfaces
	if in.NetworkHelper != nil {
		in, out := &in.NetworkHelper, &out.NetworkHelper
		*out = new(bool)
		**out = **in
	}
	in.PlacementGroup.DeepCopyInto(&out.PlacementGroup)
	if in.SwapSize != nil {
		in, out := &in.SwapSize, &out.SwapSize
		*out = new(int64)
		**out = **in
	}
	if in.Kernel != nil {
		in, out := &in.Kernel, &out.Kernel
		*out = new(string)
		**out = **in
	}
	if in.BootSize != nil {
		in, out := &in.BootSize, &out.BootSize
		*out = new(int)
		**out = **in
	}
	if in.IPv4 != nil {
		in, out := &in.IPv4, &out.IPv4
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WatchdogEnabled != nil {
		in, out := &in.WatchdogEnabled, &out.WatchdogEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Alerts != nil {
		in, out := &in.Alerts, &out.Alerts
		*out = new(InstanceAlerts)
		**out = **in
	}
	if in.BackupSchedule != nil {
		in, out := &in.BackupSchedule, &out.BackupSchedule
		*out = new(InstanceBackupSchedule)
		**out = **in
	}
	if in.Locks != nil {
		in, out := &in.Locks, &out.Locks
		*out = make([]InstanceLockType, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceSpec.
func (in *InstanceSpec) DeepCopy() *InstanceSpec {
	if in == nil {
		return nil
	}
	out := new(InstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceSpecs) DeepCopyInto(out *InstanceSpecs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceSpecs.
func (in *InstanceSpecs) DeepCopy() *InstanceSpecs {
	if in == nil {
		return nil
	}
	out := new(InstanceSpecs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceStatus) DeepCopyInto(out *InstanceStatus) {
	*out = *in
	in.Created.DeepCopyInto(&out.Created)
	in.Updated.DeepCopyInto(&out.Updated)
	in.Backups.DeepCopyInto(&out.Backups)
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IPv4 != nil {
		in, out := &in.IPv4, &out.IPv4
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Specs = in.Specs
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceStatus.
func (in *InstanceStatus) DeepCopy() *InstanceStatus {
	if in == nil {
		return nil
	}
	out := new(InstanceStatus)
	in.DeepCopyInto(out)
	return out
}
